package com.ruoyi.web.controller.projectmanagement;
import com.ruoyi.common.annotation.Log; import com.ruoyi.common.core.controller.BaseController; import com.ruoyi.common.core.domain.AjaxResult; import com.ruoyi.common.enums.BusinessType; import com.ruoyi.projectmanagement.team.domain.ProjectMember; import com.ruoyi.projectmanagement.team.domain.ProjectRole; import com.ruoyi.projectmanagement.team.service.IProjectTeamService; import java.util.List; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/projectManagement/team") public class ProjectTeamController extends BaseController { private final IProjectTeamService service; public ProjectTeamController(IProjectTeamService s){service=s;}
@PreAuthorize("@ss.hasPermi('projectManagement:project:query')") @GetMapping("/{projectId}/members") public AjaxResult members(@PathVariable Long projectId,@RequestParam(required=false)String status){ProjectMember f=new ProjectMember();f.setProjectId(projectId);f.setStatus(status);return success(service.members(f));}
@PreAuthorize("@ss.hasPermi('projectManagement:project:edit')") @Log(title="项目团队成员",businessType=BusinessType.INSERT) @PostMapping("/{projectId}/members") public AjaxResult add(@PathVariable Long projectId,@RequestBody List<ProjectMember> members){service.addMembers(projectId,members,getUsername());return success();}
@PreAuthorize("@ss.hasPermi('projectManagement:project:edit')") @Log(title="项目团队成员",businessType=BusinessType.UPDATE) @PutMapping("/member") public AjaxResult edit(@RequestBody ProjectMember member){return toAjax(service.updateMember(member,getUsername()));}
@PreAuthorize("@ss.hasPermi('projectManagement:project:edit')") @Log(title="项目团队成员退出",businessType=BusinessType.UPDATE) @PostMapping("/member/{id}/exit") public AjaxResult exit(@PathVariable Long id){return toAjax(service.exitMember(id,getUsername()));}
@PreAuthorize("@ss.hasPermi('projectManagement:project:query')") @GetMapping("/{projectId}/roles") public AjaxResult roles(@PathVariable Long projectId){return success(service.roles(projectId));}
@PreAuthorize("@ss.hasPermi('projectManagement:project:edit')") @PostMapping("/{projectId}/role") public AjaxResult addRole(@PathVariable Long projectId,@RequestBody ProjectRole role){role.setProjectId(projectId);return toAjax(service.addRole(role,getUsername()));}
@PreAuthorize("@ss.hasPermi('projectManagement:project:edit')") @PutMapping("/role") public AjaxResult editRole(@RequestBody ProjectRole role){return toAjax(service.updateRole(role,getUsername()));}}
