-- 类型：结构 / 注释
-- 适用版本：V2 预算与成本阶段 4 → 当前
-- 前置条件：45_work_package_budget.sql、46_project_actual_cost.sql 已执行
-- 可重复执行：是（仅刷新字段注释，不改变列定义）
-- 数据风险：无
-- 回退方式：无需回退；注释为元数据，不影响数据

ALTER TABLE `pm_cost_category` MODIFY COLUMN `cost_category_id` bigint AUTO_INCREMENT COMMENT '成本类别主键ID';
ALTER TABLE `pm_cost_category` MODIFY COLUMN `parent_id` bigint DEFAULT 0 COMMENT '上级类别ID，0表示根节点';
ALTER TABLE `pm_cost_category` MODIFY COLUMN `ancestors` varchar(500) DEFAULT 0 COMMENT '祖先节点ID链，逗号分隔';
ALTER TABLE `pm_cost_category` MODIFY COLUMN `category_code` varchar(50) COMMENT '类别编码，全局唯一，保存后锁定';
ALTER TABLE `pm_cost_category` MODIFY COLUMN `category_name` varchar(100) COMMENT '类别名称，同一上级下唯一';
ALTER TABLE `pm_cost_category` MODIFY COLUMN `level_no` tinyint COMMENT '层级，1-3';
ALTER TABLE `pm_cost_category` MODIFY COLUMN `allow_manual_entry` char(1) DEFAULT 1 COMMENT '是否允许手工填报，0否1是';
ALTER TABLE `pm_cost_category` MODIFY COLUMN `finance_account_code` varchar(64) NULL COMMENT '财务科目编码（预留）';
ALTER TABLE `pm_cost_category` MODIFY COLUMN `finance_account_name` varchar(128) NULL COMMENT '财务科目名称（预留）';
ALTER TABLE `pm_cost_category` MODIFY COLUMN `system_flag` char(1) DEFAULT 0 COMMENT '系统预置标记，1是0否';
ALTER TABLE `pm_cost_category` MODIFY COLUMN `status` char(1) DEFAULT 0 COMMENT '状态，0启用1停用';
ALTER TABLE `pm_cost_category` MODIFY COLUMN `sort_order` int DEFAULT 0 COMMENT '同级排序';
ALTER TABLE `pm_cost_category` MODIFY COLUMN `description` varchar(500) NULL COMMENT '说明';
ALTER TABLE `pm_cost_category` MODIFY COLUMN `create_by` varchar(64) NULL DEFAULT '' COMMENT '创建人账号';
ALTER TABLE `pm_cost_category` MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间';
ALTER TABLE `pm_cost_category` MODIFY COLUMN `update_by` varchar(64) NULL DEFAULT '' COMMENT '最后修改人账号';
ALTER TABLE `pm_cost_category` MODIFY COLUMN `update_time` datetime NULL COMMENT '最后修改时间';
ALTER TABLE `pm_professional_role` MODIFY COLUMN `professional_role_id` bigint AUTO_INCREMENT COMMENT '专业角色主键ID';
ALTER TABLE `pm_professional_role` MODIFY COLUMN `role_code` varchar(50) COMMENT '角色编码，全局唯一';
ALTER TABLE `pm_professional_role` MODIFY COLUMN `role_name` varchar(100) COMMENT '角色名称';
ALTER TABLE `pm_professional_role` MODIFY COLUMN `role_description` varchar(500) NULL COMMENT '角色说明';
ALTER TABLE `pm_professional_role` MODIFY COLUMN `system_flag` char(1) DEFAULT 0 COMMENT '系统预置标记，1是0否';
ALTER TABLE `pm_professional_role` MODIFY COLUMN `status` char(1) DEFAULT 0 COMMENT '状态，0启用1停用';
ALTER TABLE `pm_professional_role` MODIFY COLUMN `sort_order` int DEFAULT 0 COMMENT '排序';
ALTER TABLE `pm_professional_role` MODIFY COLUMN `create_by` varchar(64) NULL DEFAULT '' COMMENT '创建人账号';
ALTER TABLE `pm_professional_role` MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间';
ALTER TABLE `pm_professional_role` MODIFY COLUMN `update_by` varchar(64) NULL DEFAULT '' COMMENT '最后修改人账号';
ALTER TABLE `pm_professional_role` MODIFY COLUMN `update_time` datetime NULL COMMENT '最后修改时间';
ALTER TABLE `pm_project` MODIFY COLUMN `project_id` bigint AUTO_INCREMENT COMMENT '项目主键ID';
ALTER TABLE `pm_project` MODIFY COLUMN `project_code` varchar(32) COMMENT '项目编码，项目管理范围内唯一';
ALTER TABLE `pm_project` MODIFY COLUMN `project_name` varchar(100) COMMENT '项目名称';
ALTER TABLE `pm_project` MODIFY COLUMN `category_id` bigint COMMENT '项目分类ID';
ALTER TABLE `pm_project` MODIFY COLUMN `manager_id` bigint NULL COMMENT '项目负责人人员ID';
ALTER TABLE `pm_project` MODIFY COLUMN `manager_user_id` bigint NULL COMMENT '项目负责人系统用户ID';
ALTER TABLE `pm_project` MODIFY COLUMN `applicant` varchar(64) NULL COMMENT '项目申请人账号';
ALTER TABLE `pm_project` MODIFY COLUMN `applicant_dept_id` bigint NULL COMMENT '申请人部门ID';
ALTER TABLE `pm_project` MODIFY COLUMN `start_date` date COMMENT '计划开始日期';
ALTER TABLE `pm_project` MODIFY COLUMN `end_date` date COMMENT '计划结束日期';
ALTER TABLE `pm_project` MODIFY COLUMN `actual_start_date` date NULL COMMENT '实际启动日期，由启动项目动作写入';
ALTER TABLE `pm_project` MODIFY COLUMN `actual_end_date` date NULL COMMENT '实际完成日期，由完成项目动作写入';
ALTER TABLE `pm_project` MODIFY COLUMN `status` varchar(20) DEFAULT 'DRAFT' COMMENT '项目状态：DRAFT草稿/PENDING_APPROVAL审批中/APPROVED已批准/ACTIVE执行中/PAUSED已暂停/COMPLETED已完成';
ALTER TABLE `pm_project` MODIFY COLUMN `progress` int DEFAULT 0 COMMENT '项目总体进度0-100';
ALTER TABLE `pm_project` MODIFY COLUMN `pause_reason` varchar(500) NULL COMMENT '最近一次暂停原因';
ALTER TABLE `pm_project` MODIFY COLUMN `project_goal` varchar(1000) COMMENT '项目目标';
ALTER TABLE `pm_project` MODIFY COLUMN `project_background` text NULL COMMENT '项目背景';
ALTER TABLE `pm_project` MODIFY COLUMN `project_scope` text NULL COMMENT '项目范围';
ALTER TABLE `pm_project` MODIFY COLUMN `out_of_scope` text NULL COMMENT '项目范围外说明';
ALTER TABLE `pm_project` MODIFY COLUMN `expected_outcome` text NULL COMMENT '预期成果';
ALTER TABLE `pm_project` MODIFY COLUMN `resource_requirement` text NULL COMMENT '资源需求';
ALTER TABLE `pm_project` MODIFY COLUMN `budget_required` char(1) DEFAULT 0 COMMENT '是否需要预算，0否1是';
ALTER TABLE `pm_project` MODIFY COLUMN `budget_amount` decimal(16,2) NULL COMMENT '项目预算总额（人民币含税）';
ALTER TABLE `pm_project` MODIFY COLUMN `budget_description` varchar(1000) NULL COMMENT '预算说明';
ALTER TABLE `pm_project` MODIFY COLUMN `major_risk` text NULL COMMENT '主要风险';
ALTER TABLE `pm_project` MODIFY COLUMN `technical_feasibility` text NULL COMMENT '技术可行性';
ALTER TABLE `pm_project` MODIFY COLUMN `resource_feasibility` text NULL COMMENT '资源可行性';
ALTER TABLE `pm_project` MODIFY COLUMN `feasibility_conclusion` text NULL COMMENT '可行性综合结论';
ALTER TABLE `pm_project` MODIFY COLUMN `initiation_version` int DEFAULT 0 COMMENT '最新立项审批版本号';
ALTER TABLE `pm_project` MODIFY COLUMN `initiation_time` datetime NULL COMMENT '最新提交立项时间';
ALTER TABLE `pm_project` MODIFY COLUMN `create_by` varchar(64) NULL DEFAULT '' COMMENT '创建人账号';
ALTER TABLE `pm_project` MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间';
ALTER TABLE `pm_project` MODIFY COLUMN `update_by` varchar(64) NULL DEFAULT '' COMMENT '最后修改人账号';
ALTER TABLE `pm_project` MODIFY COLUMN `update_time` datetime NULL COMMENT '最后修改时间';
ALTER TABLE `pm_project` MODIFY COLUMN `remark` varchar(500) NULL COMMENT '备注';
ALTER TABLE `pm_project_actual_cost` MODIFY COLUMN `actual_cost_id` bigint AUTO_INCREMENT COMMENT '实际成本记录主键ID';
ALTER TABLE `pm_project_actual_cost` MODIFY COLUMN `project_id` bigint COMMENT '项目ID';
ALTER TABLE `pm_project_actual_cost` MODIFY COLUMN `work_package_id` bigint NULL COMMENT '工作包ID，空表示项目级成本';
ALTER TABLE `pm_project_actual_cost` MODIFY COLUMN `cost_category_id` bigint COMMENT '成本类别ID';
ALTER TABLE `pm_project_actual_cost` MODIFY COLUMN `category_code` varchar(50) COMMENT '类别编码快照';
ALTER TABLE `pm_project_actual_cost` MODIFY COLUMN `category_name` varchar(100) COMMENT '类别名称快照';
ALTER TABLE `pm_project_actual_cost` MODIFY COLUMN `category_path` varchar(500) COMMENT '类别路径快照';
ALTER TABLE `pm_project_actual_cost` MODIFY COLUMN `actual_amount` decimal(16,2) COMMENT '人民币含税实际成本金额';
ALTER TABLE `pm_project_actual_cost` MODIFY COLUMN `occur_date` date COMMENT '实际发生日期';
ALTER TABLE `pm_project_actual_cost` MODIFY COLUMN `description` varchar(500) COMMENT '成本事由说明';
ALTER TABLE `pm_project_actual_cost` MODIFY COLUMN `correction_no` int DEFAULT 0 COMMENT '更正次数';
ALTER TABLE `pm_project_actual_cost` MODIFY COLUMN `create_by` varchar(64) NULL DEFAULT '' COMMENT '创建人账号';
ALTER TABLE `pm_project_actual_cost` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `pm_project_actual_cost` MODIFY COLUMN `update_by` varchar(64) NULL DEFAULT '' COMMENT '最后修改人账号';
ALTER TABLE `pm_project_actual_cost` MODIFY COLUMN `update_time` datetime NULL COMMENT '最后修改时间';
ALTER TABLE `pm_project_budget_line` MODIFY COLUMN `budget_line_id` bigint AUTO_INCREMENT COMMENT '项目预算明细主键ID';
ALTER TABLE `pm_project_budget_line` MODIFY COLUMN `project_id` bigint COMMENT '项目ID';
ALTER TABLE `pm_project_budget_line` MODIFY COLUMN `cost_category_id` bigint COMMENT '成本类别ID';
ALTER TABLE `pm_project_budget_line` MODIFY COLUMN `category_code` varchar(50) COMMENT '类别编码快照';
ALTER TABLE `pm_project_budget_line` MODIFY COLUMN `category_name` varchar(100) COMMENT '类别名称快照';
ALTER TABLE `pm_project_budget_line` MODIFY COLUMN `category_path` varchar(500) COMMENT '类别路径快照';
ALTER TABLE `pm_project_budget_line` MODIFY COLUMN `budget_amount` decimal(16,2) COMMENT '人民币含税预算金额';
ALTER TABLE `pm_project_budget_line` MODIFY COLUMN `estimation_basis` varchar(1000) COMMENT '测算依据';
ALTER TABLE `pm_project_budget_line` MODIFY COLUMN `sort_order` int DEFAULT 0 COMMENT '排序';
ALTER TABLE `pm_project_budget_line` MODIFY COLUMN `create_by` varchar(64) NULL DEFAULT '' COMMENT '创建人账号';
ALTER TABLE `pm_project_budget_line` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `pm_project_budget_line` MODIFY COLUMN `update_by` varchar(64) NULL DEFAULT '' COMMENT '最后修改人账号';
ALTER TABLE `pm_project_budget_line` MODIFY COLUMN `update_time` datetime NULL COMMENT '最后修改时间';
ALTER TABLE `pm_project_category` MODIFY COLUMN `category_id` bigint AUTO_INCREMENT COMMENT '项目分类主键ID';
ALTER TABLE `pm_project_category` MODIFY COLUMN `parent_id` bigint DEFAULT 0 COMMENT '上级分类ID，0表示根节点';
ALTER TABLE `pm_project_category` MODIFY COLUMN `ancestors` varchar(500) DEFAULT 0 COMMENT '祖先分类ID链，逗号分隔';
ALTER TABLE `pm_project_category` MODIFY COLUMN `category_code` varchar(32) COMMENT '分类编码，全局唯一';
ALTER TABLE `pm_project_category` MODIFY COLUMN `category_name` varchar(50) COMMENT '分类名称';
ALTER TABLE `pm_project_category` MODIFY COLUMN `order_num` int DEFAULT 0 COMMENT '排序';
ALTER TABLE `pm_project_category` MODIFY COLUMN `status` char(1) DEFAULT 0 COMMENT '状态，0正常1停用';
ALTER TABLE `pm_project_category` MODIFY COLUMN `create_by` varchar(64) NULL DEFAULT '' COMMENT '创建人账号';
ALTER TABLE `pm_project_category` MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间';
ALTER TABLE `pm_project_category` MODIFY COLUMN `update_by` varchar(64) NULL DEFAULT '' COMMENT '最后修改人账号';
ALTER TABLE `pm_project_category` MODIFY COLUMN `update_time` datetime NULL COMMENT '最后修改时间';
ALTER TABLE `pm_project_category` MODIFY COLUMN `remark` varchar(500) NULL COMMENT '备注';
ALTER TABLE `pm_project_deliverable` MODIFY COLUMN `deliverable_id` bigint AUTO_INCREMENT COMMENT '交付物主键ID';
ALTER TABLE `pm_project_deliverable` MODIFY COLUMN `project_id` bigint COMMENT '所属项目ID';
ALTER TABLE `pm_project_deliverable` MODIFY COLUMN `work_package_id` bigint COMMENT '所属工作包ID';
ALTER TABLE `pm_project_deliverable` MODIFY COLUMN `deliverable_name` varchar(200) COMMENT '交付物名称';
ALTER TABLE `pm_project_deliverable` MODIFY COLUMN `deliverable_type` varchar(32) COMMENT '交付物类型编码快照';
ALTER TABLE `pm_project_deliverable` MODIFY COLUMN `deliverable_type_id` bigint NULL COMMENT '交付物类型ID';
ALTER TABLE `pm_project_deliverable` MODIFY COLUMN `submission_mode` varchar(20) NULL COMMENT '提交方式：FILE文件/LINK外链/BUSINESS_OBJECT业务对象';
ALTER TABLE `pm_project_deliverable` MODIFY COLUMN `allowed_extensions` varchar(1000) NULL COMMENT '允许的文件扩展名，逗号分隔';
ALTER TABLE `pm_project_deliverable` MODIFY COLUMN `required_flag` char(1) DEFAULT 1 COMMENT '是否必交，0否1是';
ALTER TABLE `pm_project_deliverable` MODIFY COLUMN `approval_required` char(1) DEFAULT 0 COMMENT '是否需要审核，0否1是';
ALTER TABLE `pm_project_deliverable` MODIFY COLUMN `reviewer` varchar(64) DEFAULT 'admin' COMMENT '审核人账号';
ALTER TABLE `pm_project_deliverable` MODIFY COLUMN `status` varchar(32) DEFAULT 'PENDING' COMMENT '交付状态：PENDING待提交等';
ALTER TABLE `pm_project_deliverable` MODIFY COLUMN `description` varchar(500) NULL COMMENT '交付说明';
ALTER TABLE `pm_project_deliverable` MODIFY COLUMN `planned_date` date NULL COMMENT '计划交付日期';
ALTER TABLE `pm_project_deliverable` MODIFY COLUMN `acceptance_criteria` varchar(2000) NULL COMMENT '验收标准';
ALTER TABLE `pm_project_deliverable` MODIFY COLUMN `business_type` varchar(32) NULL COMMENT '关联业务类型';
ALTER TABLE `pm_project_deliverable` MODIFY COLUMN `business_id` varchar(128) NULL COMMENT '关联业务ID';
ALTER TABLE `pm_project_deliverable` MODIFY COLUMN `submit_by` varchar(64) NULL COMMENT '最近提交人账号';
ALTER TABLE `pm_project_deliverable` MODIFY COLUMN `latest_file_url` varchar(1000) NULL COMMENT '最新文件地址';
ALTER TABLE `pm_project_deliverable` MODIFY COLUMN `latest_external_url` varchar(1000) NULL COMMENT '最新外链地址';
ALTER TABLE `pm_project_deliverable` MODIFY COLUMN `create_by` varchar(64) NULL DEFAULT '' COMMENT '创建人账号';
ALTER TABLE `pm_project_deliverable` MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间';
ALTER TABLE `pm_project_deliverable` MODIFY COLUMN `update_by` varchar(64) NULL DEFAULT '' COMMENT '最后修改人账号';
ALTER TABLE `pm_project_deliverable` MODIFY COLUMN `update_time` datetime NULL COMMENT '最后修改时间';
ALTER TABLE `pm_project_deliverable_submission` MODIFY COLUMN `submission_id` bigint AUTO_INCREMENT COMMENT '提交版本主键ID';
ALTER TABLE `pm_project_deliverable_submission` MODIFY COLUMN `workflow_instance_id` bigint NULL COMMENT '审核流程实例ID';
ALTER TABLE `pm_project_deliverable_submission` MODIFY COLUMN `deliverable_id` bigint COMMENT '交付物ID';
ALTER TABLE `pm_project_deliverable_submission` MODIFY COLUMN `version_no` int COMMENT '版本号，递增';
ALTER TABLE `pm_project_deliverable_submission` MODIFY COLUMN `file_url` varchar(1000) NULL COMMENT '文件地址';
ALTER TABLE `pm_project_deliverable_submission` MODIFY COLUMN `external_url` varchar(1000) NULL COMMENT '外链地址';
ALTER TABLE `pm_project_deliverable_submission` MODIFY COLUMN `submit_by` varchar(64) COMMENT '提交人账号';
ALTER TABLE `pm_project_deliverable_submission` MODIFY COLUMN `submit_time` datetime COMMENT '提交时间';
ALTER TABLE `pm_project_deliverable_submission` MODIFY COLUMN `review_result` varchar(32) COMMENT '审核结论：SUBMITTED/APPROVED/RETURNED/DELIVERED';
ALTER TABLE `pm_project_deliverable_submission` MODIFY COLUMN `review_comment` varchar(1000) NULL COMMENT '审核意见';
ALTER TABLE `pm_project_deliverable_submission` MODIFY COLUMN `review_by` varchar(64) NULL COMMENT '审核人账号';
ALTER TABLE `pm_project_deliverable_submission` MODIFY COLUMN `review_time` datetime NULL COMMENT '审核时间';
ALTER TABLE `pm_project_deliverable_type` MODIFY COLUMN `type_id` bigint AUTO_INCREMENT COMMENT '交付物类型主键ID';
ALTER TABLE `pm_project_deliverable_type` MODIFY COLUMN `type_code` varchar(32) COMMENT '类型编码，唯一';
ALTER TABLE `pm_project_deliverable_type` MODIFY COLUMN `type_name` varchar(100) COMMENT '类型名称';
ALTER TABLE `pm_project_deliverable_type` MODIFY COLUMN `submission_mode` varchar(20) COMMENT '默认提交方式：FILE/LINK/BUSINESS_OBJECT';
ALTER TABLE `pm_project_deliverable_type` MODIFY COLUMN `default_approval_required` char(1) DEFAULT 0 COMMENT '默认是否需要审核，0否1是';
ALTER TABLE `pm_project_deliverable_type` MODIFY COLUMN `status` char(1) DEFAULT 0 COMMENT '状态，0启用1停用';
ALTER TABLE `pm_project_deliverable_type` MODIFY COLUMN `sort_order` int DEFAULT 0 COMMENT '排序';
ALTER TABLE `pm_project_deliverable_type` MODIFY COLUMN `create_by` varchar(64) NULL DEFAULT '' COMMENT '创建人账号';
ALTER TABLE `pm_project_deliverable_type` MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间';
ALTER TABLE `pm_project_deliverable_type` MODIFY COLUMN `update_by` varchar(64) NULL DEFAULT '' COMMENT '最后修改人账号';
ALTER TABLE `pm_project_deliverable_type` MODIFY COLUMN `update_time` datetime NULL COMMENT '最后修改时间';
ALTER TABLE `pm_project_deliverable_type_format` MODIFY COLUMN `id` bigint AUTO_INCREMENT COMMENT '格式主键ID';
ALTER TABLE `pm_project_deliverable_type_format` MODIFY COLUMN `type_id` bigint COMMENT '交付物类型ID';
ALTER TABLE `pm_project_deliverable_type_format` MODIFY COLUMN `file_extension` varchar(20) COMMENT '允许的文件扩展名，不含点';
ALTER TABLE `pm_project_initiation_approval` MODIFY COLUMN `approval_id` bigint AUTO_INCREMENT COMMENT '立项审批版本主键ID';
ALTER TABLE `pm_project_initiation_approval` MODIFY COLUMN `workflow_instance_id` bigint NULL COMMENT '审批流程实例ID';
ALTER TABLE `pm_project_initiation_approval` MODIFY COLUMN `project_id` bigint COMMENT '项目ID';
ALTER TABLE `pm_project_initiation_approval` MODIFY COLUMN `version_no` int COMMENT '审批版本号';
ALTER TABLE `pm_project_initiation_approval` MODIFY COLUMN `snapshot_json` longtext COMMENT '申请材料快照JSON';
ALTER TABLE `pm_project_initiation_approval` MODIFY COLUMN `submit_by` varchar(64) COMMENT '提交人账号';
ALTER TABLE `pm_project_initiation_approval` MODIFY COLUMN `submit_time` datetime COMMENT '提交时间';
ALTER TABLE `pm_project_initiation_approval` MODIFY COLUMN `status` varchar(20) DEFAULT 'PENDING' COMMENT '审批状态：PENDING/APPROVED/RETURNED';
ALTER TABLE `pm_project_initiation_approval` MODIFY COLUMN `review_by` varchar(64) NULL COMMENT '审批人账号';
ALTER TABLE `pm_project_initiation_approval` MODIFY COLUMN `review_time` datetime NULL COMMENT '审批时间';
ALTER TABLE `pm_project_initiation_approval` MODIFY COLUMN `review_comment` varchar(1000) NULL COMMENT '审批意见';
ALTER TABLE `pm_project_initiation_attachment` MODIFY COLUMN `attachment_id` bigint AUTO_INCREMENT COMMENT '附件主键ID';
ALTER TABLE `pm_project_initiation_attachment` MODIFY COLUMN `project_id` bigint COMMENT '项目ID';
ALTER TABLE `pm_project_initiation_attachment` MODIFY COLUMN `approval_id` bigint NULL COMMENT '所属审批版本ID，空表示草稿附件';
ALTER TABLE `pm_project_initiation_attachment` MODIFY COLUMN `version_no` int DEFAULT 0 COMMENT '归属审批版本号';
ALTER TABLE `pm_project_initiation_attachment` MODIFY COLUMN `section_code` varchar(32) COMMENT '附件区段：BASIC_SCHEME/RESOURCE_BUDGET/RISK_ASSESSMENT';
ALTER TABLE `pm_project_initiation_attachment` MODIFY COLUMN `file_name` varchar(255) COMMENT '文件名';
ALTER TABLE `pm_project_initiation_attachment` MODIFY COLUMN `file_url` varchar(1000) COMMENT '文件地址';
ALTER TABLE `pm_project_initiation_attachment` MODIFY COLUMN `file_size` bigint NULL COMMENT '文件大小（字节）';
ALTER TABLE `pm_project_initiation_attachment` MODIFY COLUMN `file_ext` varchar(32) NULL COMMENT '文件扩展名';
ALTER TABLE `pm_project_initiation_attachment` MODIFY COLUMN `mime_type` varchar(128) NULL COMMENT 'MIME类型';
ALTER TABLE `pm_project_initiation_attachment` MODIFY COLUMN `description` varchar(500) NULL COMMENT '附件说明';
ALTER TABLE `pm_project_initiation_attachment` MODIFY COLUMN `upload_by` varchar(64) COMMENT '上传人账号';
ALTER TABLE `pm_project_initiation_attachment` MODIFY COLUMN `upload_time` datetime COMMENT '上传时间';
ALTER TABLE `pm_project_issue` MODIFY COLUMN `issue_id` bigint AUTO_INCREMENT COMMENT '问题主键ID';
ALTER TABLE `pm_project_issue` MODIFY COLUMN `project_id` bigint COMMENT '所属项目ID';
ALTER TABLE `pm_project_issue` MODIFY COLUMN `work_package_id` bigint NULL COMMENT '关联工作包ID，可空';
ALTER TABLE `pm_project_issue` MODIFY COLUMN `task_id` bigint NULL COMMENT '关联任务ID，可空';
ALTER TABLE `pm_project_issue` MODIFY COLUMN `issue_code` varchar(64) COMMENT '问题编码，项目内唯一，如ISS-001';
ALTER TABLE `pm_project_issue` MODIFY COLUMN `issue_name` varchar(200) COMMENT '问题名称';
ALTER TABLE `pm_project_issue` MODIFY COLUMN `description` varchar(2000) NULL COMMENT '问题说明';
ALTER TABLE `pm_project_issue` MODIFY COLUMN `reporter_user_id` bigint COMMENT '提出人用户ID';
ALTER TABLE `pm_project_issue` MODIFY COLUMN `owner_id` bigint NULL COMMENT '负责人ID';
ALTER TABLE `pm_project_issue` MODIFY COLUMN `owner_user_id` bigint NULL COMMENT '负责人系统用户ID';
ALTER TABLE `pm_project_issue` MODIFY COLUMN `severity` varchar(20) DEFAULT 'MEDIUM' COMMENT '严重程度：HIGH/MEDIUM/LOW';
ALTER TABLE `pm_project_issue` MODIFY COLUMN `status` varchar(20) DEFAULT 'OPEN' COMMENT '状态：OPEN/PROCESSING/RESOLVED/CLOSED';
ALTER TABLE `pm_project_issue` MODIFY COLUMN `due_date` date NULL COMMENT '截止日期';
ALTER TABLE `pm_project_issue` MODIFY COLUMN `resolution` varchar(2000) NULL COMMENT '解决方案';
ALTER TABLE `pm_project_issue` MODIFY COLUMN `resolved_time` datetime NULL COMMENT '解决时间';
ALTER TABLE `pm_project_issue` MODIFY COLUMN `closed_time` datetime NULL COMMENT '关闭时间';
ALTER TABLE `pm_project_issue` MODIFY COLUMN `create_by` varchar(64) NULL DEFAULT '' COMMENT '创建人账号';
ALTER TABLE `pm_project_issue` MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间';
ALTER TABLE `pm_project_issue` MODIFY COLUMN `update_by` varchar(64) NULL DEFAULT '' COMMENT '最后修改人账号';
ALTER TABLE `pm_project_issue` MODIFY COLUMN `update_time` datetime NULL COMMENT '最后修改时间';
ALTER TABLE `pm_project_issue_activity` MODIFY COLUMN `activity_id` bigint AUTO_INCREMENT COMMENT '动态主键ID';
ALTER TABLE `pm_project_issue_activity` MODIFY COLUMN `issue_id` bigint COMMENT '问题ID';
ALTER TABLE `pm_project_issue_activity` MODIFY COLUMN `activity_type` varchar(20) COMMENT '动态类型：CREATED/COMMENT/STATUS/ATTACHMENT';
ALTER TABLE `pm_project_issue_activity` MODIFY COLUMN `content` varchar(2000) NULL COMMENT '动态内容';
ALTER TABLE `pm_project_issue_activity` MODIFY COLUMN `from_status` varchar(20) NULL COMMENT '状态变更前';
ALTER TABLE `pm_project_issue_activity` MODIFY COLUMN `to_status` varchar(20) NULL COMMENT '状态变更后';
ALTER TABLE `pm_project_issue_activity` MODIFY COLUMN `attachment_name` varchar(255) NULL COMMENT '附件名称';
ALTER TABLE `pm_project_issue_activity` MODIFY COLUMN `attachment_url` varchar(1000) NULL COMMENT '附件地址';
ALTER TABLE `pm_project_issue_activity` MODIFY COLUMN `operator_user_id` bigint COMMENT '操作人用户ID';
ALTER TABLE `pm_project_issue_activity` MODIFY COLUMN `create_by` varchar(64) NULL DEFAULT '' COMMENT '创建人账号';
ALTER TABLE `pm_project_issue_activity` MODIFY COLUMN `create_time` datetime COMMENT '创建时间';
ALTER TABLE `pm_project_lifecycle_log` MODIFY COLUMN `log_id` bigint AUTO_INCREMENT COMMENT '日志主键ID';
ALTER TABLE `pm_project_lifecycle_log` MODIFY COLUMN `project_id` bigint COMMENT '项目ID';
ALTER TABLE `pm_project_lifecycle_log` MODIFY COLUMN `action` varchar(20) COMMENT '生命周期动作：START/PAUSE/RESUME/COMPLETE';
ALTER TABLE `pm_project_lifecycle_log` MODIFY COLUMN `from_status` varchar(20) COMMENT '变更前状态';
ALTER TABLE `pm_project_lifecycle_log` MODIFY COLUMN `to_status` varchar(20) COMMENT '变更后状态';
ALTER TABLE `pm_project_lifecycle_log` MODIFY COLUMN `reason` varchar(500) NULL COMMENT '暂停原因或说明';
ALTER TABLE `pm_project_lifecycle_log` MODIFY COLUMN `operator` varchar(64) COMMENT '操作人账号';
ALTER TABLE `pm_project_lifecycle_log` MODIFY COLUMN `operate_time` datetime COMMENT '操作时间';
ALTER TABLE `pm_project_member` MODIFY COLUMN `member_id` bigint AUTO_INCREMENT COMMENT '成员主键ID';
ALTER TABLE `pm_project_member` MODIFY COLUMN `project_id` bigint COMMENT '项目ID';
ALTER TABLE `pm_project_member` MODIFY COLUMN `person_id` bigint NULL COMMENT '人员ID（历史兼容）';
ALTER TABLE `pm_project_member` MODIFY COLUMN `user_id` bigint NULL COMMENT '系统用户ID';
ALTER TABLE `pm_project_member` MODIFY COLUMN `role_id` bigint COMMENT '项目角色ID';
ALTER TABLE `pm_project_member` MODIFY COLUMN `professional_role_id` bigint NULL COMMENT '专业角色ID';
ALTER TABLE `pm_project_member` MODIFY COLUMN `specialty_role` varchar(100) NULL COMMENT '专业角色名称快照';
ALTER TABLE `pm_project_member` MODIFY COLUMN `responsibility` varchar(500) NULL COMMENT '职责说明';
ALTER TABLE `pm_project_member` MODIFY COLUMN `join_date` date COMMENT '加入日期';
ALTER TABLE `pm_project_member` MODIFY COLUMN `exit_date` date NULL COMMENT '退出日期';
ALTER TABLE `pm_project_member` MODIFY COLUMN `status` varchar(20) DEFAULT 'ACTIVE' COMMENT '成员状态：ACTIVE/EXITED';
ALTER TABLE `pm_project_member` MODIFY COLUMN `remark` varchar(500) NULL COMMENT '备注';
ALTER TABLE `pm_project_member` MODIFY COLUMN `create_by` varchar(64) NULL DEFAULT '' COMMENT '创建人账号';
ALTER TABLE `pm_project_member` MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间';
ALTER TABLE `pm_project_member` MODIFY COLUMN `update_by` varchar(64) NULL DEFAULT '' COMMENT '最后修改人账号';
ALTER TABLE `pm_project_member` MODIFY COLUMN `update_time` datetime NULL COMMENT '最后修改时间';
ALTER TABLE `pm_project_plan_baseline` MODIFY COLUMN `baseline_id` bigint AUTO_INCREMENT COMMENT '基线主键ID';
ALTER TABLE `pm_project_plan_baseline` MODIFY COLUMN `project_id` bigint COMMENT '项目ID';
ALTER TABLE `pm_project_plan_baseline` MODIFY COLUMN `version_no` int COMMENT '基线版本号';
ALTER TABLE `pm_project_plan_baseline` MODIFY COLUMN `source_change_id` bigint NULL COMMENT '来源变更单ID，空为V1初始基线';
ALTER TABLE `pm_project_plan_baseline` MODIFY COLUMN `snapshot_json` json COMMENT '计划快照JSON';
ALTER TABLE `pm_project_plan_baseline` MODIFY COLUMN `create_by` varchar(64) NULL DEFAULT '' COMMENT '创建人账号';
ALTER TABLE `pm_project_plan_baseline` MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间';
ALTER TABLE `pm_project_plan_change` MODIFY COLUMN `change_id` bigint AUTO_INCREMENT COMMENT '变更单主键ID';
ALTER TABLE `pm_project_plan_change` MODIFY COLUMN `change_code` varchar(64) COMMENT '变更单编号，唯一';
ALTER TABLE `pm_project_plan_change` MODIFY COLUMN `project_id` bigint COMMENT '项目ID';
ALTER TABLE `pm_project_plan_change` MODIFY COLUMN `base_baseline_id` bigint COMMENT '引用基线ID';
ALTER TABLE `pm_project_plan_change` MODIFY COLUMN `base_version_no` int COMMENT '引用基线版本号';
ALTER TABLE `pm_project_plan_change` MODIFY COLUMN `title` varchar(200) COMMENT '变更标题';
ALTER TABLE `pm_project_plan_change` MODIFY COLUMN `change_reason` varchar(2000) COMMENT '变更原因';
ALTER TABLE `pm_project_plan_change` MODIFY COLUMN `impact_description` varchar(2000) COMMENT '影响说明';
ALTER TABLE `pm_project_plan_change` MODIFY COLUMN `status` varchar(30) COMMENT '状态：DRAFT/PENDING/RETURNED/PENDING_APPLY/RECONCILE/APPLIED/WITHDRAWN';
ALTER TABLE `pm_project_plan_change` MODIFY COLUMN `workflow_instance_id` bigint NULL COMMENT '审批流程实例ID';
ALTER TABLE `pm_project_plan_change` MODIFY COLUMN `applicant_user_id` bigint COMMENT '发起人用户ID';
ALTER TABLE `pm_project_plan_change` MODIFY COLUMN `create_by` varchar(64) NULL DEFAULT '' COMMENT '创建人账号';
ALTER TABLE `pm_project_plan_change` MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间';
ALTER TABLE `pm_project_plan_change` MODIFY COLUMN `update_by` varchar(64) NULL DEFAULT '' COMMENT '最后修改人账号';
ALTER TABLE `pm_project_plan_change` MODIFY COLUMN `update_time` datetime NULL COMMENT '最后修改时间';
ALTER TABLE `pm_project_plan_change_attachment` MODIFY COLUMN `attachment_id` bigint AUTO_INCREMENT COMMENT '附件主键ID';
ALTER TABLE `pm_project_plan_change_attachment` MODIFY COLUMN `change_id` bigint COMMENT '变更单ID';
ALTER TABLE `pm_project_plan_change_attachment` MODIFY COLUMN `file_name` varchar(255) COMMENT '文件名';
ALTER TABLE `pm_project_plan_change_attachment` MODIFY COLUMN `file_url` varchar(1000) COMMENT '文件地址';
ALTER TABLE `pm_project_plan_change_audit` MODIFY COLUMN `audit_id` bigint AUTO_INCREMENT COMMENT '审计主键ID';
ALTER TABLE `pm_project_plan_change_audit` MODIFY COLUMN `change_id` bigint COMMENT '变更单ID';
ALTER TABLE `pm_project_plan_change_audit` MODIFY COLUMN `action` varchar(30) COMMENT '业务动作：CREATED/UPDATED/SUBMITTED/APPROVED/APPLY_FAILED/APPLIED等';
ALTER TABLE `pm_project_plan_change_audit` MODIFY COLUMN `operator_user_id` bigint NULL COMMENT '操作人用户ID';
ALTER TABLE `pm_project_plan_change_audit` MODIFY COLUMN `operator` varchar(64) NULL DEFAULT '' COMMENT '操作人账号';
ALTER TABLE `pm_project_plan_change_audit` MODIFY COLUMN `detail` varchar(2000) NULL COMMENT '动作详情';
ALTER TABLE `pm_project_plan_change_audit` MODIFY COLUMN `create_time` datetime NULL COMMENT '记录时间';
ALTER TABLE `pm_project_plan_change_item` MODIFY COLUMN `item_id` bigint AUTO_INCREMENT COMMENT '变更项主键ID';
ALTER TABLE `pm_project_plan_change_item` MODIFY COLUMN `change_id` bigint COMMENT '变更单ID';
ALTER TABLE `pm_project_plan_change_item` MODIFY COLUMN `module_type` varchar(30) COMMENT '变更模块：PROJECT_INFO/PROJECT_BUDGET/WORK_PACKAGE_BUDGET/WBS/TASK/DELIVERABLE/TEAM';
ALTER TABLE `pm_project_plan_change_item` MODIFY COLUMN `operation_type` varchar(20) COMMENT '操作：ADD/UPDATE/DELETE';
ALTER TABLE `pm_project_plan_change_item` MODIFY COLUMN `target_type` varchar(30) COMMENT '目标类型';
ALTER TABLE `pm_project_plan_change_item` MODIFY COLUMN `target_id` bigint NULL COMMENT '目标ID；新增时可为负值临时标识';
ALTER TABLE `pm_project_plan_change_item` MODIFY COLUMN `target_name` varchar(200) NULL COMMENT '目标名称';
ALTER TABLE `pm_project_plan_change_item` MODIFY COLUMN `before_json` json NULL COMMENT '变更前JSON';
ALTER TABLE `pm_project_plan_change_item` MODIFY COLUMN `after_json` json NULL COMMENT '变更后JSON';
ALTER TABLE `pm_project_plan_change_item` MODIFY COLUMN `item_reason` varchar(1000) NULL COMMENT '变更说明';
ALTER TABLE `pm_project_plan_change_item` MODIFY COLUMN `sort_order` int NULL DEFAULT 0 COMMENT '排序';
ALTER TABLE `pm_project_preliminary_plan` MODIFY COLUMN `plan_id` bigint AUTO_INCREMENT COMMENT 'WBS概要主键ID';
ALTER TABLE `pm_project_preliminary_plan` MODIFY COLUMN `project_id` bigint COMMENT '项目ID';
ALTER TABLE `pm_project_preliminary_plan` MODIFY COLUMN `outline_name` varchar(100) COMMENT '概要名称';
ALTER TABLE `pm_project_preliminary_plan` MODIFY COLUMN `start_date` date COMMENT '开始日期';
ALTER TABLE `pm_project_preliminary_plan` MODIFY COLUMN `end_date` date COMMENT '结束日期';
ALTER TABLE `pm_project_preliminary_plan` MODIFY COLUMN `milestone_name` varchar(200) COMMENT '关键里程碑';
ALTER TABLE `pm_project_preliminary_plan` MODIFY COLUMN `outline_description` varchar(1000) NULL COMMENT '概要说明';
ALTER TABLE `pm_project_preliminary_plan` MODIFY COLUMN `sort_order` int DEFAULT 0 COMMENT '排序';
ALTER TABLE `pm_project_preliminary_plan` MODIFY COLUMN `converted_wbs_id` bigint NULL COMMENT '转换生成的顶层WBS节点ID';
ALTER TABLE `pm_project_preliminary_plan` MODIFY COLUMN `create_by` varchar(64) NULL DEFAULT '' COMMENT '创建人账号';
ALTER TABLE `pm_project_preliminary_plan` MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间';
ALTER TABLE `pm_project_preliminary_plan` MODIFY COLUMN `update_by` varchar(64) NULL DEFAULT '' COMMENT '最后修改人账号';
ALTER TABLE `pm_project_preliminary_plan` MODIFY COLUMN `update_time` datetime NULL COMMENT '最后修改时间';
ALTER TABLE `pm_project_role` MODIFY COLUMN `role_id` bigint AUTO_INCREMENT COMMENT '项目角色主键ID';
ALTER TABLE `pm_project_role` MODIFY COLUMN `project_id` bigint DEFAULT 0 COMMENT '项目ID';
ALTER TABLE `pm_project_role` MODIFY COLUMN `role_code` varchar(32) COMMENT '角色编码';
ALTER TABLE `pm_project_role` MODIFY COLUMN `role_name` varchar(64) COMMENT '角色名称';
ALTER TABLE `pm_project_role` MODIFY COLUMN `system_flag` char(1) DEFAULT 0 COMMENT '系统预置标记，1是0否';
ALTER TABLE `pm_project_role` MODIFY COLUMN `status` char(1) DEFAULT 0 COMMENT '状态，0启用1停用';
ALTER TABLE `pm_project_role` MODIFY COLUMN `sort_order` int DEFAULT 0 COMMENT '排序';
ALTER TABLE `pm_project_role` MODIFY COLUMN `create_by` varchar(64) NULL DEFAULT '' COMMENT '创建人账号';
ALTER TABLE `pm_project_role` MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间';
ALTER TABLE `pm_project_role` MODIFY COLUMN `update_by` varchar(64) NULL DEFAULT '' COMMENT '最后修改人账号';
ALTER TABLE `pm_project_role` MODIFY COLUMN `update_time` datetime NULL COMMENT '最后修改时间';
ALTER TABLE `pm_project_task` MODIFY COLUMN `task_id` bigint AUTO_INCREMENT COMMENT '任务主键ID';
ALTER TABLE `pm_project_task` MODIFY COLUMN `project_id` bigint COMMENT '所属项目ID';
ALTER TABLE `pm_project_task` MODIFY COLUMN `work_package_id` bigint COMMENT '所属工作包ID';
ALTER TABLE `pm_project_task` MODIFY COLUMN `parent_task_id` bigint DEFAULT 0 COMMENT '上级任务ID，0为顶层';
ALTER TABLE `pm_project_task` MODIFY COLUMN `task_code` varchar(96) COMMENT '任务层级编码';
ALTER TABLE `pm_project_task` MODIFY COLUMN `task_type` varchar(20) COMMENT '任务类型：SUMMARY汇总/EXECUTION执行';
ALTER TABLE `pm_project_task` MODIFY COLUMN `task_name` varchar(200) COMMENT '任务名称';
ALTER TABLE `pm_project_task` MODIFY COLUMN `description` varchar(2000) NULL COMMENT '任务说明';
ALTER TABLE `pm_project_task` MODIFY COLUMN `assignee_id` bigint NULL COMMENT '执行人ID';
ALTER TABLE `pm_project_task` MODIFY COLUMN `assignee_user_id` bigint NULL COMMENT '执行人系统用户ID';
ALTER TABLE `pm_project_task` MODIFY COLUMN `plan_start_date` date NULL COMMENT '计划开始日期';
ALTER TABLE `pm_project_task` MODIFY COLUMN `plan_end_date` date NULL COMMENT '计划结束日期';
ALTER TABLE `pm_project_task` MODIFY COLUMN `actual_start_date` date NULL COMMENT '实际开始日期';
ALTER TABLE `pm_project_task` MODIFY COLUMN `actual_end_date` date NULL COMMENT '实际完成日期';
ALTER TABLE `pm_project_task` MODIFY COLUMN `estimated_hours` decimal(12,2) NULL COMMENT '预计工时';
ALTER TABLE `pm_project_task` MODIFY COLUMN `actual_hours` decimal(12,2) NULL COMMENT '实际工时';
ALTER TABLE `pm_project_task` MODIFY COLUMN `priority` varchar(20) NULL COMMENT '优先级';
ALTER TABLE `pm_project_task` MODIFY COLUMN `status` varchar(20) DEFAULT 'NOT_STARTED' COMMENT '状态：NOT_STARTED/ACTIVE/PAUSED/COMPLETED';
ALTER TABLE `pm_project_task` MODIFY COLUMN `progress` int DEFAULT 0 COMMENT '进度0-100';
ALTER TABLE `pm_project_task` MODIFY COLUMN `pause_reason` varchar(500) NULL COMMENT '暂停原因';
ALTER TABLE `pm_project_task` MODIFY COLUMN `sort_order` int DEFAULT 0 COMMENT '排序';
ALTER TABLE `pm_project_task` MODIFY COLUMN `create_by` varchar(64) NULL DEFAULT '' COMMENT '创建人账号';
ALTER TABLE `pm_project_task` MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间';
ALTER TABLE `pm_project_task` MODIFY COLUMN `update_by` varchar(64) NULL DEFAULT '' COMMENT '最后修改人账号';
ALTER TABLE `pm_project_task` MODIFY COLUMN `update_time` datetime NULL COMMENT '最后修改时间';
ALTER TABLE `pm_project_task_operation_log` MODIFY COLUMN `log_id` bigint AUTO_INCREMENT COMMENT '操作日志主键ID';
ALTER TABLE `pm_project_task_operation_log` MODIFY COLUMN `task_id` bigint COMMENT '任务ID';
ALTER TABLE `pm_project_task_operation_log` MODIFY COLUMN `action` varchar(20) COMMENT '动作：START/PAUSE/RESUME/COMPLETE';
ALTER TABLE `pm_project_task_operation_log` MODIFY COLUMN `from_status` varchar(20) COMMENT '变更前状态';
ALTER TABLE `pm_project_task_operation_log` MODIFY COLUMN `to_status` varchar(20) COMMENT '变更后状态';
ALTER TABLE `pm_project_task_operation_log` MODIFY COLUMN `remark` varchar(500) NULL COMMENT '备注（暂停原因等）';
ALTER TABLE `pm_project_task_operation_log` MODIFY COLUMN `operator_user_id` bigint NULL COMMENT '操作人用户ID';
ALTER TABLE `pm_project_task_operation_log` MODIFY COLUMN `operator_name` varchar(64) COMMENT '操作人姓名';
ALTER TABLE `pm_project_task_operation_log` MODIFY COLUMN `operation_time` datetime COMMENT '操作时间';
ALTER TABLE `pm_project_task_output` MODIFY COLUMN `output_id` bigint AUTO_INCREMENT COMMENT '任务成果主键ID';
ALTER TABLE `pm_project_task_output` MODIFY COLUMN `task_id` bigint COMMENT '任务ID';
ALTER TABLE `pm_project_task_output` MODIFY COLUMN `output_name` varchar(200) COMMENT '成果名称';
ALTER TABLE `pm_project_task_output` MODIFY COLUMN `file_url` varchar(1000) COMMENT '文件地址';
ALTER TABLE `pm_project_task_output` MODIFY COLUMN `description` varchar(1000) NULL COMMENT '说明';
ALTER TABLE `pm_project_task_output` MODIFY COLUMN `create_by` varchar(64) COMMENT '创建人账号';
ALTER TABLE `pm_project_task_output` MODIFY COLUMN `create_time` datetime COMMENT '创建时间';
ALTER TABLE `pm_project_wbs_node` MODIFY COLUMN `wbs_id` bigint AUTO_INCREMENT COMMENT 'WBS节点主键ID';
ALTER TABLE `pm_project_wbs_node` MODIFY COLUMN `project_id` bigint COMMENT '所属项目ID';
ALTER TABLE `pm_project_wbs_node` MODIFY COLUMN `parent_id` bigint DEFAULT 0 COMMENT '上级节点ID，0为顶层';
ALTER TABLE `pm_project_wbs_node` MODIFY COLUMN `wbs_code` varchar(64) COMMENT '层级编码';
ALTER TABLE `pm_project_wbs_node` MODIFY COLUMN `node_type` varchar(20) COMMENT '节点类型：SUMMARY汇总/WORK_PACKAGE工作包';
ALTER TABLE `pm_project_wbs_node` MODIFY COLUMN `wbs_name` varchar(200) COMMENT '节点名称';
ALTER TABLE `pm_project_wbs_node` MODIFY COLUMN `scope_description` varchar(2000) NULL COMMENT '范围说明';
ALTER TABLE `pm_project_wbs_node` MODIFY COLUMN `owner_id` bigint NULL COMMENT '工作包负责人ID';
ALTER TABLE `pm_project_wbs_node` MODIFY COLUMN `owner_user_id` bigint NULL COMMENT '工作包负责人系统用户ID';
ALTER TABLE `pm_project_wbs_node` MODIFY COLUMN `plan_start_date` date NULL COMMENT '计划开始日期';
ALTER TABLE `pm_project_wbs_node` MODIFY COLUMN `plan_end_date` date NULL COMMENT '计划结束日期';
ALTER TABLE `pm_project_wbs_node` MODIFY COLUMN `target_start_date` date NULL COMMENT '立项批准目标开始日期';
ALTER TABLE `pm_project_wbs_node` MODIFY COLUMN `target_end_date` date NULL COMMENT '立项批准目标结束日期';
ALTER TABLE `pm_project_wbs_node` MODIFY COLUMN `target_milestone` varchar(200) NULL COMMENT '目标里程碑';
ALTER TABLE `pm_project_wbs_node` MODIFY COLUMN `acceptance_criteria` varchar(2000) NULL COMMENT '验收标准';
ALTER TABLE `pm_project_wbs_node` MODIFY COLUMN `definition_of_done` varchar(2000) NULL COMMENT '完成定义';
ALTER TABLE `pm_project_wbs_node` MODIFY COLUMN `deliverable_required` char(1) DEFAULT 0 COMMENT '是否需要正式交付物，0否1是';
ALTER TABLE `pm_project_wbs_node` MODIFY COLUMN `priority` varchar(20) NULL COMMENT '优先级';
ALTER TABLE `pm_project_wbs_node` MODIFY COLUMN `estimated_hours` decimal(12,2) NULL COMMENT '预计工时';
ALTER TABLE `pm_project_wbs_node` MODIFY COLUMN `budget_amount` decimal(16,2) NULL COMMENT '预算金额（历史展示）';
ALTER TABLE `pm_project_wbs_node` MODIFY COLUMN `status` varchar(32) DEFAULT 'NOT_STARTED' COMMENT '状态：NOT_STARTED/ACTIVE/WAITING_DELIVERY/COMPLETED';
ALTER TABLE `pm_project_wbs_node` MODIFY COLUMN `progress` int DEFAULT 0 COMMENT '进度0-100';
ALTER TABLE `pm_project_wbs_node` MODIFY COLUMN `sort_order` int DEFAULT 0 COMMENT '排序';
ALTER TABLE `pm_project_wbs_node` MODIFY COLUMN `create_by` varchar(64) NULL DEFAULT '' COMMENT '创建人账号';
ALTER TABLE `pm_project_wbs_node` MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间';
ALTER TABLE `pm_project_wbs_node` MODIFY COLUMN `update_by` varchar(64) NULL DEFAULT '' COMMENT '最后修改人账号';
ALTER TABLE `pm_project_wbs_node` MODIFY COLUMN `update_time` datetime NULL COMMENT '最后修改时间';
ALTER TABLE `pm_work_package_budget_line` MODIFY COLUMN `work_package_budget_line_id` bigint AUTO_INCREMENT COMMENT '工作包预算明细主键ID';
ALTER TABLE `pm_work_package_budget_line` MODIFY COLUMN `project_id` bigint COMMENT '项目ID';
ALTER TABLE `pm_work_package_budget_line` MODIFY COLUMN `work_package_id` bigint COMMENT '工作包ID';
ALTER TABLE `pm_work_package_budget_line` MODIFY COLUMN `cost_category_id` bigint COMMENT '成本类别ID';
ALTER TABLE `pm_work_package_budget_line` MODIFY COLUMN `category_code` varchar(50) COMMENT '类别编码快照';
ALTER TABLE `pm_work_package_budget_line` MODIFY COLUMN `category_name` varchar(100) COMMENT '类别名称快照';
ALTER TABLE `pm_work_package_budget_line` MODIFY COLUMN `category_path` varchar(500) COMMENT '类别路径快照';
ALTER TABLE `pm_work_package_budget_line` MODIFY COLUMN `budget_amount` decimal(16,2) COMMENT '人民币含税预算金额';
ALTER TABLE `pm_work_package_budget_line` MODIFY COLUMN `estimation_basis` varchar(1000) COMMENT '测算依据';
ALTER TABLE `pm_work_package_budget_line` MODIFY COLUMN `sort_order` int DEFAULT 0 COMMENT '排序';
ALTER TABLE `pm_work_package_budget_line` MODIFY COLUMN `create_by` varchar(64) NULL DEFAULT '' COMMENT '创建人账号';
ALTER TABLE `pm_work_package_budget_line` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `pm_work_package_budget_line` MODIFY COLUMN `update_by` varchar(64) NULL DEFAULT '' COMMENT '最后修改人账号';
ALTER TABLE `pm_work_package_budget_line` MODIFY COLUMN `update_time` datetime NULL COMMENT '最后修改时间';
ALTER TABLE `pm_workflow_definition` MODIFY COLUMN `definition_id` bigint AUTO_INCREMENT COMMENT '审批流定义主键ID';
ALTER TABLE `pm_workflow_definition` MODIFY COLUMN `definition_name` varchar(100) COMMENT '定义名称';
ALTER TABLE `pm_workflow_definition` MODIFY COLUMN `business_type` varchar(40) COMMENT '业务类型：PROJECT_INITIATION/DELIVERABLE_APPROVAL/PLAN_CHANGE';
ALTER TABLE `pm_workflow_definition` MODIFY COLUMN `active_version_id` bigint NULL COMMENT '当前发布版本ID';
ALTER TABLE `pm_workflow_definition` MODIFY COLUMN `status` varchar(20) DEFAULT 'ENABLED' COMMENT '定义状态：ENABLED/DISABLED';
ALTER TABLE `pm_workflow_definition` MODIFY COLUMN `create_by` varchar(64) NULL DEFAULT '' COMMENT '创建人账号';
ALTER TABLE `pm_workflow_definition` MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间';
ALTER TABLE `pm_workflow_definition` MODIFY COLUMN `update_by` varchar(64) NULL DEFAULT '' COMMENT '最后修改人账号';
ALTER TABLE `pm_workflow_definition` MODIFY COLUMN `update_time` datetime NULL COMMENT '最后修改时间';
ALTER TABLE `pm_workflow_definition_version` MODIFY COLUMN `version_id` bigint AUTO_INCREMENT COMMENT '定义版本主键ID';
ALTER TABLE `pm_workflow_definition_version` MODIFY COLUMN `definition_id` bigint COMMENT '所属定义ID';
ALTER TABLE `pm_workflow_definition_version` MODIFY COLUMN `version_no` int COMMENT '版本号';
ALTER TABLE `pm_workflow_definition_version` MODIFY COLUMN `version_status` varchar(20) COMMENT '版本状态：DRAFT/PUBLISHED';
ALTER TABLE `pm_workflow_definition_version` MODIFY COLUMN `graph_json` json COMMENT '节点图JSON';
ALTER TABLE `pm_workflow_definition_version` MODIFY COLUMN `create_by` varchar(64) NULL DEFAULT '' COMMENT '创建人账号';
ALTER TABLE `pm_workflow_definition_version` MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间';
ALTER TABLE `pm_workflow_definition_version` MODIFY COLUMN `publish_by` varchar(64) NULL COMMENT '发布人账号';
ALTER TABLE `pm_workflow_definition_version` MODIFY COLUMN `publish_time` datetime NULL COMMENT '发布时间';
ALTER TABLE `pm_workflow_event_log` MODIFY COLUMN `event_id` bigint AUTO_INCREMENT COMMENT '事件主键ID';
ALTER TABLE `pm_workflow_event_log` MODIFY COLUMN `instance_id` bigint COMMENT '流程实例ID';
ALTER TABLE `pm_workflow_event_log` MODIFY COLUMN `task_id` bigint NULL COMMENT '任务ID';
ALTER TABLE `pm_workflow_event_log` MODIFY COLUMN `event_type` varchar(30) COMMENT '事件类型';
ALTER TABLE `pm_workflow_event_log` MODIFY COLUMN `operator_user_id` bigint COMMENT '操作人用户ID';
ALTER TABLE `pm_workflow_event_log` MODIFY COLUMN `content` varchar(1000) NULL COMMENT '事件内容';
ALTER TABLE `pm_workflow_event_log` MODIFY COLUMN `create_time` datetime COMMENT '记录时间';
ALTER TABLE `pm_workflow_instance` MODIFY COLUMN `instance_id` bigint AUTO_INCREMENT COMMENT '流程实例主键ID';
ALTER TABLE `pm_workflow_instance` MODIFY COLUMN `business_type` varchar(40) COMMENT '业务类型';
ALTER TABLE `pm_workflow_instance` MODIFY COLUMN `business_id` bigint COMMENT '业务主键ID';
ALTER TABLE `pm_workflow_instance` MODIFY COLUMN `project_id` bigint COMMENT '所属项目ID';
ALTER TABLE `pm_workflow_instance` MODIFY COLUMN `definition_version_id` bigint COMMENT '使用的定义版本ID';
ALTER TABLE `pm_workflow_instance` MODIFY COLUMN `title` varchar(200) COMMENT '实例标题';
ALTER TABLE `pm_workflow_instance` MODIFY COLUMN `initiator_user_id` bigint COMMENT '发起人用户ID';
ALTER TABLE `pm_workflow_instance` MODIFY COLUMN `status` varchar(20) COMMENT '实例状态：RUNNING/APPROVED/REJECTED/WITHDRAWN';
ALTER TABLE `pm_workflow_instance` MODIFY COLUMN `current_node_key` varchar(64) NULL COMMENT '当前节点Key';
ALTER TABLE `pm_workflow_instance` MODIFY COLUMN `business_snapshot_json` json NULL COMMENT '业务快照JSON';
ALTER TABLE `pm_workflow_instance` MODIFY COLUMN `finish_time` datetime NULL COMMENT '结束时间';
ALTER TABLE `pm_workflow_instance` MODIFY COLUMN `create_by` varchar(64) NULL DEFAULT '' COMMENT '创建人账号';
ALTER TABLE `pm_workflow_instance` MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间';
ALTER TABLE `pm_workflow_instance` MODIFY COLUMN `update_by` varchar(64) NULL DEFAULT '' COMMENT '最后修改人账号';
ALTER TABLE `pm_workflow_instance` MODIFY COLUMN `update_time` datetime NULL COMMENT '最后修改时间';
ALTER TABLE `pm_workflow_task` MODIFY COLUMN `task_id` bigint AUTO_INCREMENT COMMENT '审批任务主键ID';
ALTER TABLE `pm_workflow_task` MODIFY COLUMN `instance_id` bigint COMMENT '流程实例ID';
ALTER TABLE `pm_workflow_task` MODIFY COLUMN `node_key` varchar(64) COMMENT '节点Key';
ALTER TABLE `pm_workflow_task` MODIFY COLUMN `node_name` varchar(100) COMMENT '节点名称';
ALTER TABLE `pm_workflow_task` MODIFY COLUMN `node_order` int COMMENT '节点顺序';
ALTER TABLE `pm_workflow_task` MODIFY COLUMN `status` varchar(20) COMMENT '任务状态：WAITING/PENDING/APPROVED/REJECTED/CANCELLED';
ALTER TABLE `pm_workflow_task` MODIFY COLUMN `acted_by_user_id` bigint NULL COMMENT '处理人用户ID';
ALTER TABLE `pm_workflow_task` MODIFY COLUMN `opinion` varchar(1000) NULL COMMENT '审批意见';
ALTER TABLE `pm_workflow_task` MODIFY COLUMN `acted_time` datetime NULL COMMENT '处理时间';
ALTER TABLE `pm_workflow_task` MODIFY COLUMN `create_time` datetime COMMENT '创建时间';
ALTER TABLE `pm_workflow_task_candidate` MODIFY COLUMN `task_id` bigint COMMENT '审批任务ID';
ALTER TABLE `pm_workflow_task_candidate` MODIFY COLUMN `user_id` bigint COMMENT '候选人用户ID';
ALTER TABLE `pm_workflow_task_candidate` MODIFY COLUMN `read_time` datetime NULL COMMENT '已读时间';
