package com.ruoyi.projectmanagement.team.service.impl;
import com.ruoyi.common.exception.ServiceException; import com.ruoyi.common.utils.StringUtils; import com.ruoyi.projectmanagement.person.mapper.ProjectPersonMapper; import com.ruoyi.projectmanagement.project.mapper.ProjectInfoMapper; import com.ruoyi.projectmanagement.team.domain.ProjectMember; import com.ruoyi.projectmanagement.team.domain.ProjectRole; import com.ruoyi.projectmanagement.team.mapper.ProjectTeamMapper; import com.ruoyi.projectmanagement.team.service.IProjectTeamService; import java.time.LocalDate; import java.util.List; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class ProjectTeamServiceImpl implements IProjectTeamService { private final ProjectTeamMapper mapper; private final ProjectInfoMapper projectMapper; private final ProjectPersonMapper personMapper; public ProjectTeamServiceImpl(ProjectTeamMapper m,ProjectInfoMapper p,ProjectPersonMapper person){mapper=m;projectMapper=p;personMapper=person;}
public List<ProjectMember> members(ProjectMember f){return mapper.selectMembers(f);} public List<ProjectRole> roles(Long id){return mapper.selectRoles(id);} public boolean isActiveMember(Long p,Long person){return mapper.selectActiveMember(p,person)!=null;} public int activeCount(Long p){return mapper.countActiveMembers(p);}
@Transactional public void addMembers(Long projectId,List<ProjectMember> members,String operator){assertManage(projectId,operator);assertMutable(projectId);ProjectRole defaultRole=mapper.selectSystemRole("MEMBER");for(ProjectMember m:members){if(m.getPersonId()==null)throw new ServiceException("请选择人员");if(personMapper.selectProjectPersonById(m.getPersonId())==null)throw new ServiceException("人员档案不存在");if(mapper.selectActiveMember(projectId,m.getPersonId())!=null)throw new ServiceException("人员已在项目团队中，不能重复添加");m.setProjectId(projectId);if(m.getRoleId()==null)m.setRoleId(defaultRole.getRoleId());validateRole(projectId,m.getRoleId());if(m.getJoinDate()==null)m.setJoinDate(LocalDate.now());m.setStatus("ACTIVE");m.setCreateBy(operator);mapper.insertMember(m);}}
public int updateMember(ProjectMember m,String operator){ProjectMember old=required(m.getMemberId());assertManage(old.getProjectId(),operator);assertMutable(old.getProjectId());if("PROJECT_MANAGER".equals(old.getRoleCode()))throw new ServiceException("项目负责人请通过变更项目负责人调整");validateRole(old.getProjectId(),m.getRoleId());m.setUpdateBy(operator);return mapper.updateMember(m);}
public int exitMember(Long id,String operator){ProjectMember m=required(id);assertManage(m.getProjectId(),operator);assertMutable(m.getProjectId());if("PROJECT_MANAGER".equals(m.getRoleCode()))throw new ServiceException("项目负责人不能退出团队，请先变更项目负责人");int count=mapper.countIncompleteTasks(m.getProjectId(),m.getPersonId());if(count>0)throw new ServiceException("该成员仍负责"+count+"项未完成任务，请先转交任务");m.setExitDate(LocalDate.now());m.setUpdateBy(operator);return mapper.exitMember(m);}
public int addRole(ProjectRole r,String operator){assertManage(r.getProjectId(),operator);assertMutable(r.getProjectId());r.setRoleCode("CUSTOM_"+System.currentTimeMillis());r.setSystemFlag("0");r.setStatus("0");r.setCreateBy(operator);return mapper.insertRole(r);} public int updateRole(ProjectRole r,String operator){ProjectRole old=mapper.selectRoleById(r.getRoleId());if(old==null||"1".equals(old.getSystemFlag()))throw new ServiceException("系统预置角色不可修改");assertManage(old.getProjectId(),operator);assertMutable(old.getProjectId());if("1".equals(r.getStatus())&&mapper.countRoleMembers(r.getRoleId())>0)throw new ServiceException("该角色仍有在组成员，不能停用");r.setUpdateBy(operator);return mapper.updateRole(r);}
@Transactional public void ensureManager(Long projectId,Long managerId,Long previousManagerId,String operator){ProjectRole manager=mapper.selectSystemRole("PROJECT_MANAGER"),core=mapper.selectSystemRole("CORE_MEMBER");if(previousManagerId!=null&&!previousManagerId.equals(managerId)){ProjectMember old=mapper.selectActiveMember(projectId,previousManagerId);if(old!=null){old.setRoleId(core.getRoleId());old.setUpdateBy(operator);mapper.updateMember(old);}}ProjectMember m=new ProjectMember();m.setProjectId(projectId);m.setPersonId(managerId);m.setRoleId(manager.getRoleId());m.setSpecialtyRole("项目经理");m.setResponsibility("负责项目总体目标、计划与协调");m.setJoinDate(LocalDate.now());m.setStatus("ACTIVE");m.setCreateBy(operator);mapper.insertMember(m);}
private ProjectMember required(Long id){ProjectMember m=mapper.selectMemberById(id);if(m==null)throw new ServiceException("项目成员不存在");return m;} private void validateRole(Long projectId,Long roleId){ProjectRole r=mapper.selectRoleById(roleId);if(r==null||(!Long.valueOf(0).equals(r.getProjectId())&&!projectId.equals(r.getProjectId())))throw new ServiceException("项目角色不可用");} private void assertMutable(Long id){String status=projectMapper.selectProjectInfoById(id).getStatus();if("COMPLETED".equals(status))throw new ServiceException("项目已完成，团队仅可查看");if("PENDING_APPROVAL".equals(status))throw new ServiceException("项目正在立项审批中，拟定团队不能修改");} private void assertManage(Long id,String operator){var p=projectMapper.selectProjectInfoById(id);if(p==null)throw new ServiceException("项目不存在");if(!"admin".equalsIgnoreCase(operator)&&(StringUtils.isBlank(p.getManagerCode())||!p.getManagerCode().equalsIgnoreCase(operator)))throw new ServiceException("只有项目负责人或admin可以管理项目团队");}}
