create table if not exists agent_file (
    id bigint not null auto_increment comment '文件主键',
    resource_id varchar(64) not null comment '对外不可猜测的资源标识',
    user_id bigint not null comment '所属用户ID',
    conversation_id bigint default null comment '本地会话ID',
    message_id bigint default null comment '本地消息ID',
    dify_conversation_id varchar(128) default null comment 'Dify会话ID',
    dify_file_id varchar(128) default null comment 'Dify原始文件ID',
    tool_name varchar(100) default null comment '生成文件的工具标识',
    file_name varchar(255) not null comment '展示文件名',
    storage_name varchar(255) not null comment '磁盘存储文件名',
    relative_path varchar(500) not null comment '相对存储路径',
    extension varchar(32) default null comment '文件扩展名',
    media_type varchar(128) default null comment 'MIME类型',
    file_kind varchar(32) not null comment '文件类别',
    file_size bigint not null comment '文件大小，单位字节',
    file_hash varchar(64) default null comment 'SHA-256摘要',
    preview_mode varchar(20) not null comment 'BROWSER预览或DOWNLOAD下载',
    status varchar(20) not null default 'AVAILABLE' comment 'AVAILABLE可用、FAILED失败、DELETED已删除',
    create_by varchar(64) default '',
    create_time datetime default current_timestamp,
    update_by varchar(64) default '',
    update_time datetime default current_timestamp,
    primary key (id),
    unique key uk_agent_file_resource (resource_id),
    key idx_agent_file_user_time (user_id, create_time),
    key idx_agent_file_conversation (conversation_id),
    key idx_agent_file_message (message_id)
) engine=InnoDB comment='Agent生成文件';
