-- 采购到货入库与库存余额基础表
-- 说明：业务表使用 Long 自增主键，审计字段沿用 RuoYi BaseEntity，不使用软删除。

CREATE TABLE IF NOT EXISTS purchase_order (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  order_code VARCHAR(64) NOT NULL COMMENT '采购订单编号',
  supplier_code VARCHAR(64) DEFAULT NULL COMMENT '供应商编码快照',
  supplier_name VARCHAR(255) DEFAULT NULL COMMENT '供应商名称快照',
  order_date DATE NOT NULL COMMENT '订单日期',
  expected_date DATE DEFAULT NULL COMMENT '预计到货日期',
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '单据状态：DRAFT/SUBMITTED/APPROVED/PARTIAL_RECEIVED/COMPLETED/CANCELLED',
  approved_by VARCHAR(64) DEFAULT NULL COMMENT '审核人',
  approved_time DATETIME DEFAULT NULL COMMENT '审核时间',
  total_quantity DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '订单总数量',
  total_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '订单总金额',
  currency VARCHAR(16) NOT NULL DEFAULT 'CNY' COMMENT '币种',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  create_by VARCHAR(64) DEFAULT NULL COMMENT '创建人',
  create_time DATETIME DEFAULT NULL COMMENT '创建时间',
  update_by VARCHAR(64) DEFAULT NULL COMMENT '更新人',
  update_time DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_purchase_order_code (order_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购订单主表';

CREATE TABLE IF NOT EXISTS purchase_order_line (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  order_id BIGINT NOT NULL COMMENT '采购订单主表ID',
  line_no INT NOT NULL COMMENT '行号',
  material_id BIGINT NOT NULL COMMENT '物料ID',
  material_code VARCHAR(64) NOT NULL COMMENT '物料编码快照',
  material_name VARCHAR(255) NOT NULL COMMENT '物料名称快照',
  spec VARCHAR(500) DEFAULT NULL COMMENT '规格快照',
  model VARCHAR(255) DEFAULT NULL COMMENT '型号快照',
  unit VARCHAR(64) NOT NULL COMMENT '计量单位',
  order_quantity DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '采购数量',
  received_quantity DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '已到货数量',
  qualified_quantity DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '合格数量',
  inbound_quantity DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '已入库数量',
  unit_price DECIMAL(18,6) DEFAULT NULL COMMENT '单价',
  tax_rate DECIMAL(8,4) DEFAULT NULL COMMENT '税率',
  amount DECIMAL(18,2) DEFAULT NULL COMMENT '明细金额',
  planned_date DATE DEFAULT NULL COMMENT '计划到货日期',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  create_by VARCHAR(64) DEFAULT NULL COMMENT '创建人',
  create_time DATETIME DEFAULT NULL COMMENT '创建时间',
  update_by VARCHAR(64) DEFAULT NULL COMMENT '更新人',
  update_time DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_purchase_order_line (order_id, line_no),
  KEY idx_purchase_order_line_material (material_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购订单明细';

CREATE TABLE IF NOT EXISTS purchase_receipt (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  receipt_code VARCHAR(64) NOT NULL COMMENT '到货单编号',
  supplier_code VARCHAR(64) DEFAULT NULL COMMENT '供应商编码快照',
  supplier_name VARCHAR(255) DEFAULT NULL COMMENT '供应商名称快照',
  receipt_date DATE NOT NULL COMMENT '实际到货日期',
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '状态：DRAFT/CONFIRMED/PARTIAL/COMPLETED/CANCELLED',
  inspection_status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '检验状态：NOT_REQUIRED/PENDING/PASSED/PARTIAL/FAILED',
  approved_by VARCHAR(64) DEFAULT NULL COMMENT '审核人',
  approved_time DATETIME DEFAULT NULL COMMENT '审核时间',
  inspection_by VARCHAR(64) DEFAULT NULL COMMENT '质检人',
  inspection_time DATETIME DEFAULT NULL COMMENT '质检时间',
  total_quantity DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '到货总数量',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  create_by VARCHAR(64) DEFAULT NULL COMMENT '创建人',
  create_time DATETIME DEFAULT NULL COMMENT '创建时间',
  update_by VARCHAR(64) DEFAULT NULL COMMENT '更新人',
  update_time DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_purchase_receipt_code (receipt_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购到货单主表';

CREATE TABLE IF NOT EXISTS purchase_receipt_line (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  receipt_id BIGINT NOT NULL COMMENT '到货单主表ID',
  line_no INT NOT NULL COMMENT '行号',
  source_order_id BIGINT NOT NULL COMMENT '来源采购订单ID',
  source_order_code VARCHAR(64) NOT NULL COMMENT '来源采购订单编号快照',
  source_order_line_id BIGINT NOT NULL COMMENT '来源采购订单明细ID',
  source_order_line_no INT NOT NULL COMMENT '来源采购订单明细行号快照',
  material_id BIGINT NOT NULL COMMENT '物料ID',
  material_code VARCHAR(64) NOT NULL COMMENT '物料编码快照',
  material_name VARCHAR(255) NOT NULL COMMENT '物料名称快照',
  spec VARCHAR(500) DEFAULT NULL COMMENT '规格快照',
  unit VARCHAR(64) NOT NULL COMMENT '单位',
  received_quantity DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '实际到货数量',
  qualified_quantity DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '检验合格数量',
  rejected_quantity DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '检验不合格数量',
  pending_quantity DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '待检验数量',
  inbound_quantity DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '已入库数量',
  lot_no VARCHAR(128) DEFAULT NULL COMMENT '批次号',
  production_date DATE DEFAULT NULL COMMENT '生产日期',
  expiry_date DATE DEFAULT NULL COMMENT '有效期',
  warehouse_code VARCHAR(64) DEFAULT NULL COMMENT '入库仓库编码',
  warehouse_name VARCHAR(255) DEFAULT NULL COMMENT '入库仓库名称快照',
  location_code VARCHAR(64) DEFAULT NULL COMMENT '入库库位编码',
  location_name VARCHAR(255) DEFAULT NULL COMMENT '入库库位名称快照',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  create_by VARCHAR(64) DEFAULT NULL COMMENT '创建人',
  create_time DATETIME DEFAULT NULL COMMENT '创建时间',
  update_by VARCHAR(64) DEFAULT NULL COMMENT '更新人',
  update_time DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_purchase_receipt_line (receipt_id, line_no),
  KEY idx_purchase_receipt_line_material (material_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购到货单明细';

CREATE TABLE IF NOT EXISTS purchase_inbound (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  inbound_code VARCHAR(64) NOT NULL COMMENT '入库单编号',
  inbound_date DATE NOT NULL COMMENT '入库日期',
  warehouse_code VARCHAR(64) NOT NULL COMMENT '默认入库仓库编码',
  warehouse_name VARCHAR(255) DEFAULT NULL COMMENT '仓库名称快照',
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '状态：DRAFT/CONFIRMED/POSTED/CANCELLED',
  approved_by VARCHAR(64) DEFAULT NULL COMMENT '审核人',
  approved_time DATETIME DEFAULT NULL COMMENT '审核时间',
  total_quantity DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '入库总数量',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  create_by VARCHAR(64) DEFAULT NULL COMMENT '创建人',
  create_time DATETIME DEFAULT NULL COMMENT '创建时间',
  update_by VARCHAR(64) DEFAULT NULL COMMENT '更新人',
  update_time DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_purchase_inbound_code (inbound_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购入库单主表';

CREATE TABLE IF NOT EXISTS purchase_inbound_line (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  inbound_id BIGINT NOT NULL COMMENT '入库单主表ID',
  line_no INT NOT NULL COMMENT '行号',
  source_receipt_id BIGINT NOT NULL COMMENT '来源到货单ID',
  source_receipt_code VARCHAR(64) NOT NULL COMMENT '来源到货单编号快照',
  source_receipt_line_id BIGINT NOT NULL COMMENT '来源到货单明细ID',
  source_receipt_line_no INT NOT NULL COMMENT '来源到货单明细行号快照',
  source_order_id BIGINT NOT NULL COMMENT '来源采购订单ID',
  source_order_code VARCHAR(64) NOT NULL COMMENT '来源采购订单编号快照',
  source_order_line_id BIGINT NOT NULL COMMENT '来源采购订单明细ID',
  source_order_line_no INT NOT NULL COMMENT '来源采购订单明细行号快照',
  material_id BIGINT NOT NULL COMMENT '物料ID',
  material_code VARCHAR(64) NOT NULL COMMENT '物料编码快照',
  material_name VARCHAR(255) NOT NULL COMMENT '物料名称快照',
  spec VARCHAR(500) DEFAULT NULL COMMENT '规格快照',
  unit VARCHAR(64) NOT NULL COMMENT '单位',
  inbound_quantity DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '本次入库数量',
  lot_no VARCHAR(128) DEFAULT NULL COMMENT '批次号',
  production_date DATE DEFAULT NULL COMMENT '生产日期',
  expiry_date DATE DEFAULT NULL COMMENT '有效期',
  warehouse_code VARCHAR(64) NOT NULL COMMENT '仓库编码',
  warehouse_name VARCHAR(255) DEFAULT NULL COMMENT '仓库名称快照',
  location_code VARCHAR(64) NOT NULL DEFAULT '' COMMENT '库位编码',
  location_name VARCHAR(255) DEFAULT NULL COMMENT '库位名称快照',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  create_by VARCHAR(64) DEFAULT NULL COMMENT '创建人',
  create_time DATETIME DEFAULT NULL COMMENT '创建时间',
  update_by VARCHAR(64) DEFAULT NULL COMMENT '更新人',
  update_time DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_purchase_inbound_line (inbound_id, line_no),
  KEY idx_purchase_inbound_line_material (material_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购入库单明细';

CREATE TABLE IF NOT EXISTS inventory_balance (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  material_id BIGINT NOT NULL COMMENT '物料ID',
  material_code VARCHAR(64) NOT NULL COMMENT '物料编码快照',
  material_name VARCHAR(255) NOT NULL COMMENT '物料名称快照',
  warehouse_code VARCHAR(64) NOT NULL COMMENT '仓库编码',
  warehouse_name VARCHAR(255) DEFAULT NULL COMMENT '仓库名称快照',
  location_code VARCHAR(64) DEFAULT NULL COMMENT '库位编码',
  location_name VARCHAR(255) DEFAULT NULL COMMENT '库位名称快照',
  lot_no VARCHAR(128) NOT NULL DEFAULT '' COMMENT '批次号',
  production_date DATE DEFAULT NULL COMMENT '生产日期',
  expiry_date DATE DEFAULT NULL COMMENT '有效期',
  unit VARCHAR(64) NOT NULL COMMENT '计量单位',
  quantity DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '库存总数量',
  available_quantity DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '可用库存数量',
  locked_quantity DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '已锁定库存数量',
  status VARCHAR(32) NOT NULL DEFAULT 'NORMAL' COMMENT '库存状态：NORMAL/FROZEN/LOCKED',
  last_inbound_date DATE DEFAULT NULL COMMENT '最后入库日期',
  last_update_time DATETIME DEFAULT NULL COMMENT '库存最后变动时间',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  create_by VARCHAR(64) DEFAULT NULL COMMENT '创建人',
  create_time DATETIME DEFAULT NULL COMMENT '创建时间',
  update_by VARCHAR(64) DEFAULT NULL COMMENT '更新人',
  update_time DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_inventory_balance (material_id, warehouse_code, location_code, lot_no),
  KEY idx_inventory_balance_material (material_id),
  KEY idx_inventory_balance_warehouse (warehouse_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库存余额表';

CREATE TABLE IF NOT EXISTS inventory_transaction (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  transaction_type VARCHAR(32) NOT NULL COMMENT '事务类型：INBOUND/INBOUND_REVERSE',
  business_id BIGINT NOT NULL COMMENT '业务单据ID',
  business_code VARCHAR(64) NOT NULL COMMENT '业务单据编号快照',
  business_line_id BIGINT NOT NULL COMMENT '业务单据明细ID',
  material_id BIGINT NOT NULL COMMENT '物料ID',
  material_code VARCHAR(64) NOT NULL COMMENT '物料编码快照',
  material_name VARCHAR(255) NOT NULL COMMENT '物料名称快照',
  warehouse_code VARCHAR(64) NOT NULL COMMENT '仓库编码',
  location_code VARCHAR(64) NOT NULL DEFAULT '' COMMENT '库位编码',
  lot_no VARCHAR(128) NOT NULL DEFAULT '' COMMENT '批次号',
  unit VARCHAR(64) NOT NULL COMMENT '计量单位',
  quantity DECIMAL(18,6) NOT NULL COMMENT '变动数量，入库为正、弃审为负',
  source_receipt_line_id BIGINT DEFAULT NULL COMMENT '来源送货单明细ID',
  source_order_line_id BIGINT DEFAULT NULL COMMENT '来源采购订单明细ID',
  create_by VARCHAR(64) DEFAULT NULL COMMENT '创建人',
  create_time DATETIME DEFAULT NULL COMMENT '创建时间',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  KEY idx_inventory_transaction_business (business_id, business_line_id),
  KEY idx_inventory_transaction_material (material_id, warehouse_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库存事务流水';
