-- 采购单据类型字段
ALTER TABLE purchase_order ADD COLUMN bill_type VARCHAR(30) DEFAULT 'NORMAL' COMMENT '单据类型';
ALTER TABLE purchase_receipt ADD COLUMN bill_type VARCHAR(30) DEFAULT NULL COMMENT '单据类型：DIRECT/PURCHASE_ORDER';
ALTER TABLE purchase_inbound ADD COLUMN bill_type VARCHAR(30) DEFAULT NULL COMMENT '单据类型：DIRECT/RECEIPT';
